anatomical_map = {
    "liver": [5],
    "stomach": [6],
    "left upper pulmonary lobe": [10],
    "left lower pulmonary lobe": [11],
    "right upper pulmonary lobe": [12],
    "right middle pulmonary lobe": [13],
    "right lower pulmonary lobe": [14],
    "esophagus": [15],
    "tracheal airway": [16],
    "heart": [51],
    "thoracic aorta": [52],
    "pulmonary vein": [53],
    "left atrial appendage": [61],
    "superior vena cava": [62],
    "inferior vena cava": [63],
    "sternum": [116],
    "rib cartilage": [117],
    "lungs": [10, 11, 12, 13, 14],
    "thoracic vertebrae": list(range(32, 44)),
    "ribs": list(range(92, 116)),
    "right ribs": list(range(104, 116)),
    "left ribs": list(range(92, 101)),
    "right lung": [10, 11],
    "left lung": [12, 13, 14]
}