hf_TrainingArguments:
  dataloader_num_workers: 64
  learning_rate: 5.e-5
  logging_steps: 50
  max_steps: 25000
  output_dir: [OUTPUTDIR]
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 8
  remove_unused_columns: false
  save_steps: 5000
  weight_decay: 0.0001
  warmup_steps: 25
input_file: [INPUT_PARQUET]
llm_args:
  bert_encoder_layers: 4
  model_class: BertModel
  model_id: BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext
vision_args:
  feature_dim: 1280
  llm_emb_dim: 768
  model_args:
    global_pool: ''
    in_chans: 1
    model_name: tf_efficientnet_b0.in1k
    num_classes: 0
    pretrained: true
  model_class: EfficientNetViT
  nhead: 8
  seqlen: 258
predict_transform:
  - constant_values: 0.0
    name: SpatialPad
    spatial_size:
      - 384
      - 320
      - 256
  - name: CenterSpatialCrop
    roi_size:
      - 384
      - 320
      - 256
  - name: Resize
    spatial_size:
      - 256
      - 160
      - 128
train_transform:
  - constant_values: 0.0
    name: SpatialPad
    spatial_size:
      - 416
      - 336
      - 256
  - name: CenterSpatialCrop
    roi_size:
      - 416
      - 336
      - 256
  - name: RandRotate
    prob: 0.5
    range_x: 0.261799166
    range_y: 0.261799166
    range_z: 0.261799166
  - max_zoom: 1.1
    min_zoom: 0.9
    name: RandZoom
    prob: 0.5
  - constant_values: 0.0
    name: SpatialPad
    spatial_size:
      - 384
      - 320
      - 256
  - name: CenterSpatialCrop
    roi_size:
      - 384
      - 320
      - 256
  - name: Resize
    spatial_size:
      - 256
      - 160
      - 128
train_transform_imgonly:
  - name: RandGaussianNoise
    std: 0.01
    prob: 0.5
  - name: RandShiftIntensity
    offsets: 0.01
    prob: 0.5
